//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_Color_Shop_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDH
    {
        public int MaDonHang { get; set; }
        public int MaChiTietSP { get; set; }
        public Nullable<int> SoLuongMua { get; set; }
        public Nullable<decimal> DonGiaBan { get; set; }
    
        public virtual SPtheoMau SPtheoMau { get; set; }
        public virtual DonHang DonHang { get; set; }
    }
}
