//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_Color_Shop_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.SPtheoMaus = new HashSet<SPtheoMau>();
        }
        [Display(Name = "Mã sản phẩm")]
        public int MaSanPham { get; set; }
        [Display(Name = "Mã sản phẩm")]
        [RegularExpression("^[a-zA-Z].*", ErrorMessage = "Tên phải bắt đầu bằng chữ")]
        public string TenSanPham { get; set; }
        [Display(Name = "Mã sản phẩm")]
        public Nullable<int> MaPhanLoai { get; set; }
        [RegularExpression("^[0-9]+$")]
        public Nullable<decimal> GiaNhap { get; set; }
        public Nullable<decimal> DonGiaBanNhoNhat { get; set; }
        public Nullable<decimal> DonGiaBanLonNhat { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        [RegularExpression("^[a-zA-Z].*", ErrorMessage = "Mô tả phải bắt đầu bằng chữ")]
        public string MoTaNgan { get; set; }
        [RegularExpression("^(.+)+'.jpg'$", ErrorMessage = "File ảnh")]
        public string AnhDaiDien { get; set; }
        public Nullable<bool> NoiBat { get; set; }
        public Nullable<int> MaPhanLoaiPhu { get; set; }
    
        public virtual PhanLoai PhanLoai { get; set; }
        public virtual PhanLoaiPhu PhanLoaiPhu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPtheoMau> SPtheoMaus { get; set; }
    }
}
